---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tic-game
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tic-game
  template:
    metadata:
      labels:
        app: tic-game
    spec:
      containers:
      - name: tic-game
        image: ahd0611/tic-game:latest
        ports:
        - containerPort: 3000   # Use port 3000

---
apiVersion: v1
kind: Service
metadata:
  name: tic-game-service
spec:
  selector:
    app: tic-game
  ports:
  - protocol: TCP
    port: 80                 # Expose port 80
    targetPort: 3000
  type: LoadBalancer
